### PR TITLE
Remove standard-engine, update dependencies

### PR DESCRIPTION
**Pull request by misteroneill**
This takes from using standard-engine and its horrible output to using ESLint directly (programmatically), which gives us nice things like colored output for a visual separation between warnings and errors!

### CODE REVIEW

**Comment by dmlap** [comment]
LGTM

**Comment by BrandonOCasey** [comment]
may want to update the readme with this change

**Comment by misteroneill** [comment]
Yeah, definitely. Rewriting it now.

**Comment by misteroneill** [comment]
This will still need a version update for eslint-config-videojs.

**Pull request merged**
